#!/usr/bin/env python

import sys, json
from plurk_oauth.PlurkAPI import PlurkAPI
import os,time
from termcolor import colored

rows, columns = os.popen('stty size', 'r').read().split()
LIMIT=20
USER_HOME=os.path.expanduser('~')
CONFIG_PATH = os.path.join(USER_HOME,'.plurk-cli')
if not os.path.isdir(CONFIG_PATH):
  try:
    os.mkdir(CONFIG_PATH)
  except:
    print 'Make configure path %s Faild' % CONFIG_PATH
    exit()
LAST_TIME_READ = os.path.join(CONFIG_PATH,'last_time_read')
plurk = PlurkAPI('XHYblwvESclp','fWojEnk17x15SFwVy3oAzCTDytvYEZ11')
authorize_file = os.path.join(CONFIG_PATH,'authorize_keys')
if not os.path.isfile(authorize_file):
  try:
    plurk.authorize()
    f = open(authorize_file,'w+')
    i = dict()
    i = plurk._oauth.oauth_token
    f.write(json.dumps(i))
  except:
    print 'there is something wrong when writing the config to %s.' % authorize_file
    exit()
else:
  try:
    f = open(authorize_file,'r')
    i = dict()
    i = json.loads(f.read())
    plurk.authorize(i['oauth_token'],i['oauth_token_secret'])
  except:
    print 'there is something wrong when reading the config to %s.' % authorize_file
    exit()



def b36en(num):
  alphabet = [ chr(i) for i in ( range(48,58) + range(97,123) ) ]
  if (num == 0):
    return alphabet[0]
  arr = []
  base = len(alphabet)
  while num:
    rem = num % base
    num = num // base
    arr.append(alphabet[rem])
  arr.reverse()
  return ''.join(arr)

def main(argv):
  api = {
    'mute':   '/APP/Timeline/mutePlurks',
    'unmute': '/APP/Timeline/unmutePlurks',
    'favor':  '/APP/Timeline/favoritePlurks',
    'unfavor':'/APP/Timeline/unfavoritePlurks',
    'mar':    '/APP/Timeline/markAsRead'}
  if argv[0]=='add':
    add_plurk(argv[1:])
  elif argv[0] == 'get':
    data={'limit':LIMIT}
    if '--offset' in argv:
      try:
        offset = argv[argv.index('--offset')+1]
        test_time = time.strptime(offset,'%Y-%m-%dT%H:%M:%S')
      except:
        pass
      else:
        data['offset'] = offset
    if '--filter' in argv:
      filter_var = argv[argv.index('--filter')+1]
      if filter_var in ['only_user', 'only_responded', 'only_private', 'only_favorite']:
        data['filter'] = filter_var
      else:
        data['filter'] = None
    p = plurk.callAPI('/APP/Timeline/getPlurks',data)
    out_put(p)
  elif argv[0] in ['del', 'edit']:
    try:
      plurk_id = int(argv[1])
    except:
      print 'Please input Plurk id in integer not Base36.'
      exit()
    data = {'plurk_id':plurk_id}
    if argv[0] == 'del':
      p = plurk.callAPI('/APP/Timeline/plurkDelete',data)
    elif argv[0] == 'edit' and len(argv) == 3:
      data['content'] = argv[2]
      p = plurk.callAPI('/APP/Timeline/plurkEdit',data)
    else:
      print "there is something wrong in argvalues."
    if p.has_key('error_text'):
      print p['error_text']
    else:
      print 'OK!'
  elif argv[0] == 'resp_add':
    add_resp(argv[1:])
  elif argv[0] == 'resp_get':
    get_resp(argv[1:])
  elif argv[0] == 'resp_del':
    data = {'plurk_id': int(argv[1]),'response_id':int(argv[2])}
    p = plurk.callAPI('/APP/Responses/responseDelete',data)
    if p.has_key('error_text'):
      print 'ERROR! %s.' % p['error_text']
    else:
      print 'Success!'
  elif argv[0] == 'get_unread_count':
    p = plurk.callAPI('/APP/Polling/getUnreadCount')
    f = open(LAST_TIME_READ,'r+')
    last_time = f.read()
    f.close()
    a = time.strptime(last_time,'%a, %d %b %Y %H:%M:%S %Z')
    data={'offset':time.strftime('%Y-%m-%dT%H:%M:%S',a)}
    np = plurk.callAPI('/APP/Polling/getPlurks',data)
    p['new'] = len(np['plurks'])
    print "New: %d All: %d My: %d Private: %d Responded: %d Favorite: %d" % \
          (p['new'],p['all'],p['my'],p['private'],p['responded'],p['favorite'])
  elif argv[0] == 'get_unread':
    data = {'limit': LIMIT}
    if '--new' in argv:
      get_last_timeLine_read()
    else:
      if '--my' in argv:
        data['filter'] = 'my'
      elif '--responded' in argv:
        data['filter'] = 'responded'
      elif '--private' in argv:
        data['filter'] = 'private'
      elif '--favorite' in argv:
        data['filter'] = 'favorite'
      p = plurk.callAPI('/APP/Timeline/getUnreadPlurks',data)
      rp = out_put(p)
      if rp['plurk_ids'] and '--withmar' in argv:
        plurk.callAPI('/APP/Timeline/markAsRead',{'ids':rp['plurk_ids'],'note_position':'true'})
  elif argv[0] in list(api.keys()):
    data = {'ids':[int(i) for i in argv[1:]]}
    p = plurk.callAPI(api[argv[0]],data)
    if p['success_text'] != "ok":
      print "It's something wrong"
    else:
      print "OK!"
  elif argv[0] in ['replurk','unreplurk']:
    data = {'ids':[int(i) for i in argv[1:]]}
    p = plurk.callAPI('/APP/Timeline/'+argv[0],data)
    for i, j in p['results'].items():
      if j['success']:
        print '%s %s success.' % (i, argv[0])
      else:
        print '%s %s error. %s' % (i, argv[0], j['error'])
  elif argv[0] == 'get_user_pub':
    data = dict()
    data['user_id'] = argv[1] if argv[1][0] != '@' else argv[1][1:]
    data['limit']   = LIMIT
    if '--offset' in argv:
      try:
        offset = argv[argv.index('--offset')+1]
        test_time = time.strptime(offset,'%Y-%m-%dT%H:%M:%S')
      except:
        pass
      else:
        data['offset'] = offset
    p = plurk.callAPI('/APP/Timeline/getPublicPlurks',data)
    out_put(p)
  else:
    print """USAGE:    
    plurk add [qualifier] [content] [-p -nc -fc]
          get [--offset [time]]
          resp_add [plurk_id] [qualifier] [content]
          resp_get [plurk_id]
          resp_del [plurk_id] [resp_id]
          get_unread_count
          get_unread [--new --my --responded --private --favorite]
          del [plurk_id]
          edit [plurk_id] [content]
          mute [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          unmute [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          favor [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          unfavor [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          mar [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          replurk [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          unreplurk [plurk_id#1 plurk_id#2 plurk_id#3 ...]
          get_user_pub [user_id]

* readmore on doc."""


def add_plurk(argv):
  data = {'content':argv[1],'qualifier':argv[0],'lang':'tr_ch','limit': LIMIT}
  if '-p' in argv:
    data['limited_to'] = [0]
  if '-nc' in argv:
    data['no_comments'] = 1
  elif '-fc' in argv:
    data['no_comments'] = 2
  p = plurk.callAPI('/APP/Timeline/plurkAdd',data)
  if not p.has_key('error_text'):
    print 'url: http://www.plurk.com/p/'+b36en(p['plurk_id']) + '\nplurk_id: '+ str(p['plurk_id'])
  else:
    print p['error_text']


def get_last_timeLine_read():
  f = open(LAST_TIME_READ,'r+')
  last_time = f.read()
  f.close()
  try:
    a = time.strptime(last_time,'%a, %d %b %Y %H:%M:%S %Z')
  except:
    last_time = time.strftime('%a, %d %b %Y %H:%M:%S %Z')
    a = time.strptime(last_time,'%a, %d %b %Y %H:%M:%S %Z')
  data={'offset':time.strftime('%Y-%m-%dT%H:%M:%S',a),'limit':LIMIT+10}
  p = plurk.callAPI('/APP/Polling/getPlurks',data)
  rp = out_put(p)
  last_time = rp['last_time'] if rp['last_time'] else last_time
  f = open(LAST_TIME_READ,'w+')
  f.write(last_time)
  f.close()


def out_put(p):
  last_time=None
  first_time = None
  plurk_ids = []
  print '-'*int(columns)
  for h, i in enumerate(reversed(p['plurks'])):
    out_put_plurk(i,p['plurk_users'])
    print '-'*int(columns)
    if h == 0:
      first_time = i['posted']
    last_time = i['posted']
    plurk_ids = plurk_ids + [i['plurk_id']]
  if first_time != None and last_time != None:
    print 'Offset From: %s End: %s' % (time.strftime('%Y-%m-%dT%H:%M:%S',time.strptime(first_time,'%a, %d %b %Y %H:%M:%S %Z')),time.strftime('%Y-%m-%dT%H:%M:%S',time.strptime(last_time,'%a, %d %b %Y %H:%M:%S %Z')))
  return {'last_time':last_time,'first_time':first_time,'plurk_ids':plurk_ids}

def out_put_plurk(i,p):
  if not i.has_key('qualifier_translated'):
    i['qualifier_translated'] = None
  qu = qualifier_color( i['qualifier'], i['qualifier_translated'])
  plurk_uname = user_coloer(p[str(i['owner_id'])])
  if i.has_key('replurker_id') and i['replurker_id']:
    replurk_uname = user_coloer(p[str(i['replurker_id'])])
    print '%s %s %s %s' % ( replurk_uname, qualifier_color('replurk'), plurk_uname, qu)
  else:
    print plurk_uname+' ' + qu
  print i['content_raw']
  l = str(i['response_count'])+ ' response(s)' if i['response_count'] else 'no response'
  k = colored(l,'white','on_red') if i['is_unread'] == 1 else l
  m = 'plurk_id: '+str(i['plurk_id'])
  j = {'c':{},'uc':{}}
  if i.has_key('favorite') and i['favorite']:
    j['uc']['f'] = ' F '
    j['c']['f']  = colored(j['uc']['f'],'grey','on_cyan', attrs=['dark'])
  if i.has_key('replurked') and i['replurked']:
    j['uc']['r'] = ' R '
    j['c']['r']  = colored(j['uc']['r'],'grey','on_green', attrs=['dark'])
  if (int(i['plurk_type']) | 2) is 3:
    j['uc']['p'] = ' P '
    j['c']['p']  = colored(j['uc']['p'],'grey','on_yellow', attrs=['dark'])
  if int(i['is_unread']) is 2:
    j['uc']['m'] = ' M '
    j['c']['m']  = colored(j['uc']['m'],'grey','on_white', attrs=['dark'])
  print ' '*(int(columns)-len(' '.join(list(j['uc'].values())+[l,m]))) + ' '.join(list(j['c'].values())+[k,m])


def out_put_resp(p):
  for i in p['responses']:
    if not i.has_key('qualifier_translated'):
      i['qualifier_translated'] = None
    qu = qualifier_color( i['qualifier'], i['qualifier_translated'])
    plurk_uname = user_coloer(p['friends'][str(i['user_id'])])
    print plurk_uname+' ' + qu
    print i['content_raw']
    j = 'respond_id: '+str(i['id'])
    print ' '*(int(columns)-len(j)) + j
    print '-'*int(columns)
  print 'Total: %d response(s)' % len(p['responses'])

def user_coloer(plurk_user):
  plurk_uname = plurk_user['display_name'] if plurk_user.has_key('display_name') else plurk_user['nick_name']
  plurk_uname = plurk_uname + '(@%s)' % plurk_user['nick_name']
  if not plurk_user.has_key('name_color'):
    plurk_user['name_color'] = None
  if plurk_user['name_color'] == '0A9C17':
    plurk_uname = colored(plurk_uname, 'green', attrs=['bold'])
  elif plurk_user['name_color'] == '2264D6':
    plurk_uname = colored(plurk_uname, 'blue', attrs=['bold'])
  elif plurk_user['name_color'] == 'E41227':
    plurk_uname = colored(plurk_uname, 'red', attrs=['bold'])
  else:
    plurk_uname = colored(plurk_uname, attrs=['bold'])
  return plurk_uname

def qualifier_color(qu,qu_tr=None):
  if qu in ['loves', 'likes', 'shares', 'gives', 'says', 'is']:
    bg = 'on_red'
  elif qu in ['hates', 'has', 'was', ':', 'freestyle']:
    bg = 'on_grey'
  elif qu in ['wants', 'wishes', 'needs', 'replurk']:
    bg = 'on_green'
  elif qu in ['will', 'hopes', 'asks']:
    bg = 'on_magenta'
  elif qu in ['wonders']:
    bg = 'on_cyan'
  elif qu in ['feels', 'thinks']:
    bg = 'on_blue'
  if not qu_tr:
    qu_tr = qu
  return colored(qu_tr, 'white', bg)

def add_resp(argv):
  data=dict()
  data['plurk_id']=int(argv[0])
  data['qualifier']=argv[1]
  data['content'] =argv[2]
  p = plurk.callAPI('/APP/Responses/responseAdd',data)
  print 'respond id: %d' % p['id']


def get_resp(argv):
  p = plurk.callAPI('/APP/Timeline/getPlurk',{'plurk_id':argv[0]})
  print '='*int(columns)
  out_put_plurk(p['plurk'],p['plurk_users'])
  print '='*int(columns)
  p = plurk.callAPI('/APP/Responses/get',{'plurk_id':argv[0]})
  out_put_resp(p)


if __name__ == '__main__':
  main(sys.argv[1:])
